In [153]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from xlsxwriter.utility import xl_cell_to_rowcol

In [154]:
from email.header import Header


data = pd.read_excel(r"C:\Users\kabir\AppData\Local\Programs\DREAM\Portfolio\Test.xlsx", index_col=0, header=[0])
data

                                  Acquirer        Target
Particulars
Revenue                        157263.0195     135925.76
Gross Profit                      120301.6         95086
Less:Operating expenses                NaN           NaN
Selling general & admin         69386.0996    75845.9325
EBITDA                          50915.5004    19240.0675
Less:D&A                             17925             0
Add:Other income                     31758       9012.11
EBIT                            32990.5004    19240.0675
Less:Interest expenses                   0             0
NaN                                    NaN           NaN
EBT                             64748.5004    28252.1775
Less: Income tax                9712.27506   4237.826625
Net income                     55036.22534  24014.350875
NaN                                    NaN           NaN
Shares outstanding                  554.55    194.209842
Tax rates                             0.15          0.15
Current market price                1482.2          2430
Market Cap                 81574693.198948     1347556.5
NaN                                    NaN           NaN
NaN                                    NaN           NaN
Current rate of interest            0.0633           NaN
Current rate of borrowing            0.088           NaN
NaN                                    NaN           NaN
Sources of Funds                         %             %
Cash                                   NaN           0.1
Debt                                   NaN           0.3
Acquirer's stock                       NaN           0.6

In [155]:
#Creating a Dictionary to store Merger and Acquisition Data, with required Index
from email import header


Ind = ['Particulars','Premium','Share price acquirer', 'Acquisition price of target', 'Acquisition value', 'Cash used',
'Debt used', 'Shares used', 'No. Shares issued by acquirer', 'Pre merger Income of acquirer', 
'Shares outstanding of acquirer', 'EPS of acquirer standalone', 'Post merger EPS calculation', 'Revenue', 'Gross profit', 
'Less: Operating expenses', 'Selling general & admin', 'EBITDA', 'Less:D&A', 'Add : Other Income', 'EBIT', 
'Less:Interest on debt', 'Less: Interest foregone', 'PBT', 'Less: Income tax', 
'Net Income', 'Outstanding Diluted shares of combined company', 'EPS of combined company', 'EPS of acquirer standalone',
 'Accretive/Dilutive', 'Accretion/Dilution', 'Accretion/Dilution (%)']
M_A = pd.Series(index = Ind)

C:\Users\kabir\AppData\Local\Temp\ipykernel_26408\603406540.py:12: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  M_A = pd.Series(index = Ind)

In [156]:
def M_AND_A(data, Model, percent):
    #Premium [1:2] = Percent from input
    Model[1:2] = percent
    #Share price acquirer [2:3] = Share price of acquirer from Data  [16:17, :1]
    Model[2:3] = round(data.iloc[16:17, :1], 2)
    #Acquisition price of target[3:4] = percent[1:2]+1 * target share price data[16:17]
    Model[3:4] = round(data.iloc[16:17, 1:2] * (1+Model[1:2][0]),2)
    #Acquisition value [4:5] = number of outstanding shares (data[14:15]) * Acquisition price of the target [3:4]
    Model[4:5] = round((data.iloc[14:15, 1:2] * Model[3:4][0]),2)
    #Cash used [5:6] = Acquisition value [4:5] * percent of cash used as source of fund [24:25]
    Model[5:6] = round(data.iloc[24:25, 1:2].values[0][0] * Model[4:5][0],2)
    Model[6:7] = round(data.iloc[25:26, 1:2].values[0][0] * Model[4:5][0],2)
    Model[7:8] = round(data.iloc[26:27, 1:2].values[0][0] * Model[4:5][0],2)
    Model[8:9] = round(Model[7:8][0]/Model[2:3][0],2)
    Model[9:10] = round(data.iloc[12:13, :1].values[0][0],2)
    Model[10:11] = round(data.iloc[14:15, :1].values[0][0],2)
    Model[11:12] = round(Model[9:10][0]/Model[10:11][0],2)
    Model[12:13] = "-----------------"
    Model[13:14] = round(data.iloc[0:1, 1:2].values[0][0] + data.iloc[0:1, :1].values[0][0],2)
    Model[14:15] = round(data.iloc[1:2, 1:2].values[0][0] + data.iloc[1:2, :1].values[0][0],2)
    Model[15:16] = "-----------------"
    Model[16:17] = round(data.iloc[3:4, 1:2].values[0][0] + data.iloc[3:4, :1].values[0][0],2)
    Model[17:18] = round(Model[14:15][0] - Model[16:17][0],2)
    Model[18:19] = round(data.iloc[5:6, 1:2].values[0][0] + data.iloc[5:6, :1].values[0][0],2)
    Model[19:20] = round(data.iloc[6:7, 1:2].values[0][0] + data.iloc[6:7, :1].values[0][0],2)
    Model[20:21] = round((Model[17:18][0] - (Model[18:19][0]) + Model[19:20][0]),2)
    Model[21:22] = round((data.iloc[21:22, :1] * Model[6:7][0]),2)
    Model[22:23] = round((data.iloc[20:21, :1] * Model[5:6][0]),2)
    Model[23:24] = round((Model[20:21][0] - (Model[21:22][0] + Model[22:23][0])),2)
    Model[24:25] = round(data.iloc[15:16, :1] * Model[23:24][0] ,2)
    Model[25:26] = round((Model[23:24][0] - Model[24:25][0]), 2)
    Model[26:27] = round((Model[8:9][0] + Model[10:11][0]), 2)
    Model[27:28] = round((Model[25:26][0] / Model[26:27][0]), 2)
    Model[28:29] = Model[11:12][0]
    if Model[27:28][0] > Model[28:29][0] : Model[29:30] = "ACCRETIVE" 
    else : Model[29:30] = "DILUTIVE"
    Model[30:31] = Model[27:28][0] - Model[28:29][0]
    Model[31:32] = round((Model[30:31][0]/ Model[28:29][0])*100, 2)
    return Model

In [157]:
MerAqu = pd.DataFrame(index=Ind)
for i in [float(s) for s in input("insert Premiums").split(",")]:
    output = M_AND_A(data, M_A, i)
    MerAqu[str(i*100) + "%"] = output
MerAqu = MerAqu[2:]
MerAqu

,20.0%,35.0%,50.0%,65.0%,80.0%
Share price acquirer,1482.2,1482.2,1482.2,1482.2,1482.2
Acquisition price of target,2916.0,3280.5,3645.0,4009.5,4374.0
Acquisition value,566315.900137,637105.387655,707894.875172,778684.362689,849473.850206
Cash used,56631.59,63710.54,70789.49,77868.44,84947.39
Debt used,169894.77,191131.62,212368.46,233605.31,254842.16
Shares used,339789.54,382263.23,424736.93,467210.62,509684.31
No. Shares issued by acquirer,229.25,257.9,286.56,315.21,343.87
Pre merger Income of acquirer,55036.23,55036.23,55036.23,55036.23,55036.23
Shares outstanding of acquirer,554.55,554.55,554.55,554.55,554.55
EPS of acquirer standalone,99.24,99.24,99.24,99.24,99.24
Post merger EPS calculation,-----------------,-----------------,-----------------,-----------------,-----------------
Revenue,293188.78,293188.78,293188.78,293188.78,293188.78
Gross profit,215387.6,215387.6,215387.6,215387.6,215387.6
Less: Operating expenses,-----------------,-----------------,-----------------,-----------------,-----------------
Selling general & admin,145232.03,145232.03,145232.03,145232.03,145232.03
EBITDA,70155.57,70155.57,70155.57,70155.57,70155.57
Less:D&A,17925,17925,17925,17925,17925
Add : Other Income,40770.11,40770.11,40770.11,40770.11,40770.11
EBIT,93000.68,93000.68,93000.68,93000.68,93000.68
Less:Interest on debt,14950.73976,16819.58256,18688.42448,20557.26728,22426.11008
Less: Interest foregone,3584.779647,4032.877182,4480.974717,4929.072252,5377.169787
PBT,74465.16,72148.22,69831.28,67514.34,65197.4
Less: Income tax,11169.774,10822.233,10474.692,10127.151,9779.61
Net Income,63295.39,61325.99,59356.59,57387.19,55417.79
Outstanding Diluted shares of combined company,783.8,812.45,841.11,869.76,898.42
EPS of combined company,80.75,75.48,70.57,65.98,61.68
EPS of acquirer standalone,99.24,99.24,99.24,99.24,99.24
Accretive/Dilutive,DILUTIVE,DILUTIVE,DILUTIVE,DILUTIVE,DILUTIVE
Accretion/Dilution,-18.49,-23.76,-28.67,-33.26,-37.56
Accretion/Dilution (%),-18.63,-23.94,-28.89,-33.51,-37.85

In [158]:
#Accessing workbook to format the output in excel
# MerAqu.to_excel("MA.xlsx")
writer = pd.ExcelWriter('MA.xlsx', engine='xlsxwriter')
MerAqu.to_excel(writer, sheet_name='Merger_and_acquisition')

workbook = writer.book
worksheet = writer.sheets['Merger_and_acquisition']

In [159]:
# # Setting zoom level
worksheet.set_zoom(90)

In [160]:
# #setting Header Format
header_format = workbook.add_format({
        "valign": "vcenter",
        "align": "center",
        "bg_color": "#008080",
         "bold": True,
        'font_color': '#000080',
         'border' : 3, 
         'border_color': ''#D3D3D3'
    })

In [161]:
#add title
title = "Merger and Acquisition"
#merge cells
format = workbook.add_format({
    'bold': True,
    "align": "center"
})
format.set_font_size(24)
format.set_font_color("#000080")
format.set_border(5)
worksheet.merge_range('A1:K1', title, format)
worksheet.set_row(2, 30) # Set the header row height to 15
# puting it all together
# Write the column headers with the defined format.
# for col_num, value in enumerate(dsf.columns.values):
#     #print(col_num, value)
#     worksheet.write(2, col_num, value, header_format)

0

In [162]:
# Full border formatting for conditional formatted cells
full_border = workbook.add_format({ "border" : 1, "border_color": "#D3D3D3"})

# Add a number format for cells with money.
currency_format = workbook.add_format({'num_format': '#,##0.00'})
percent_fmt = workbook.add_format({'num_format': '0.0%'})

# Adjust the column width.
worksheet.set_column('B:K', 20)

0

In [163]:
# # Numbers formatting
worksheet.set_column('B:B', 12, currency_format)
worksheet.set_column('C:C', 12, currency_format)
worksheet.set_column('F:F', 12, currency_format)
worksheet.set_column('E:E', 12, currency_format)
worksheet.set_column('D:D', 12, currency_format)
# worksheet.write("B31",percent_fmt)
# Percent formatting
# worksheet.set_column('D:D', 20, percent_fmt)

0

In [164]:
#Formating specificrows
from re import S


ADformat = workbook.add_format({
        "valign": "vcenter",
        "align": "center",
        "bg_color": "#FFFFFF",
         "bold": True,
        'font_color': '#000000',
        'border' : 3,
        'border_color': '#D3D3D3'})

worksheet.set_row(28, 20, ADformat)

# #Formatting first Column
FCformat = workbook.add_format({
        "valign": "vcenter",
        "align": "left",
        "bg_color": "#FFFFFF",
         "bold": True,
        'font_color': '#000000',
         'border' : 3, 
         'border_color': '#D3D3D3'
    })
FCformat.set_valign('vcenter')
FCformat.set_bold(True)
FCformat.set_font_size(14)
FCformat.set_align('Left')
worksheet.set_column("A:A", 50, FCformat)

0

In [165]:
#Advance output
writer.save()